# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Language to be generated'
        default: 'java'
        required: true

jobs:
  api-binding:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate client
      run: |
        docker run -u 1001 --rm --workdir /github/workspace -v "$GITHUB_WORKSPACE":"/github/workspace" \
          openapitools/openapi-generator-cli generate \
          -i /github/workspace/api.yml \
          -g ${{ github.event.inputs.language }} \
          -c /github/workspace/config.yml \
          -o /github/workspace/generated \
          --skip-validate-spec

    - name: Show files
      working-directory: ./generated
      run: |
        ls
    
    - name: Remove File build.gradle
      uses: JesseTG/rm@v1.0.2
      with:
        path: /github/workspace/generated/build.gradle
    
    - name: Remove File gradlew
      uses: JesseTG/rm@v1.0.2
      with:
        path: /github/workspace/generated/gradlew
        
    - name: Remove File gradlew.bat
      uses: JesseTG/rm@v1.0.2
      with:
        path: /github/workspace/generated/gradlew.bat
    
    - name: Remove gradlew wrapper
      uses: JesseTG/rm@v1.0.2
      with:
        path: /github/workspace/generated/gradle/

    - name: Add and push
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Dart Bot
        author_email: noreply@github-bot.de
        default_author: user_info
        message: 'Updating api'



